name: CI/CD for Kotlin Hello World

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Compile and Run Kotlin Program
        run: |
          kotlinc main.kt -include-runtime -d hello_world.jar
          java -jar hello_world.jar
